version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - .:/app
    networks:
      - exlibris
    env_file:
      - .env
    depends_on:
      - pg
      - mysql
    entrypoint: sh -c "npm run start:dev:inspect"

  pg:
    image: 'postgres:16-alpine'
    env_file:
      - .env
    volumes:
      - ./db/pg:/var/lib/postgresql/data
    networks:
      - exlibris
    ports:
      - '5432:5432'

  mysql:
    image: 'mysql:8.2.0'
    env_file:
      - .env
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - exlibris
    ports:
      - '3306:3306'

networks:
  exlibris:
    name: exlibris_network
